#!/usr/bin/env bash
### ASDF
if [ -r /opt/homebrew/opt/asdf/libexec/asdf.sh ]; then
    . /opt/homebrew/opt/asdf/libexec/asdf.sh
    enabled=1
fi

if [ ! -o $enabled ]; then
    if [ -o $color_prompt ]; then
        printf "\xE2\x9C\x93 asdf\n"
    else
        printf "\e[32m\xE2\x9C\x93 asdf\e[m\n"
    fi
fi

unset enabled
