#!/usr/bin/env bash
### Proxy
enable_proxy() {
    export http_proxy=http://127.0.0.1:1087
    export HTTP_PROXY=http://127.0.0.1:1087
    export https_proxy=http://127.0.0.1:1087
    export HTTPS_PROXY=http://127.0.0.1:1087

    if [ -o $color_prompt ]; then
        printf "\xE2\x9C\x93 proxy\n"
    else
        printf "\e[32m\xE2\x9C\x93 proxy\e[m\n"
    fi
}

disable_proxy() {
    unset http_proxy
    unset HTTP_PROXY
    unset https_proxy
    unset HTTPS_PROXY

    if [ -o $color_prompt ]; then
        printf "\xE2\x9C\x98 proxy\n"
    else
        printf "\e[31m\xE2\x9C\x98 proxy\e[m\n"
    fi
}

if [ -o $DISABLE_PROXY ]; then
    enable_proxy
else
    disable_proxy
fi

unset DISABLE_PROXY
