syntax on
filetype on

set nocompatible nobackup autochdir
set number ruler incsearch hlsearch autoindent expandtab
set shiftwidth=4 tabstop=4 softtabstop=4 foldmethod=marker
set mouse=a backspace=indent,eol,start fileencoding=utf-8
