#!/usr/bin/env bash
### If not running interactively, don't do anything
case $- in
    *i* )
    ;;
    * )
        return
    ;;
esac

### Check windows size after each command
shopt -s checkwinsize

### Append to the history file
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

### Check if color prompted
case $TERM in
    xterm-color | xterm-256color )
        color_prompt=1
    ;;
esac

### PS
if [ -o $color_prompt ]; then
    PS1="\n{\t} [\u@\h]: \w\n=> "
elif [ $USER == "root" ]; then
    PS1="\n{\t} [\e[91m\u\e[m@\h]: \e[91m\$PWD\e[m\n=> "
else
    PS1="\n{\t} [\u@\h]: \e[36m\w\e[m\n=> "
fi
PS2="==> "
PS3="===> "
PS4="====> "
export PS1 PS2 PS3 PS4

### Get current bash environment
ENVDIR=$(dirname $(dirname $BASH))

### Set environments
if [ $ENVDIR != "/" ]; then
    PATH="$ENVDIR/bin:$ENVDIR/sbin:$PATH"
fi
PATH="$HOME/.bin:$HOME/.volta/bin:$PATH"
export PATH
export HOMEBREW_NO_INSTALL_FROM_API=1
export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
DISABLE_PROXY=1

### Read additional configs
if [ -d $HOME/.bashrc.d/ ]; then
    for cfile in $HOME/.bashrc.d/*; do
        . $cfile
    done
    unset cfile
fi

unset ENVDIR
