# If not running interactively, don't do anything
case $- in
  *i* )
  ;;
  * )
    return
  ;;
esac

# Check windows size after each command
shopt -s checkwinsize

# Append to the history file
shopt -s histappend
# History file length
HISTSIZE=1000
HISTFILESIZE=2000

# Check if color prompted
case "$TERM" in
  xterm-color | xterm-256color )
    color_prompt=1
  ;;
esac

# PS
if [ -o $color_prompt ]; then
  PS1="\n{\t} [\u@\h]: \w\n\$ "
elif [ "$USER" == "root" ]; then
  PS1="\n{\t} [\e[91m\u\e[m@\h]: \e[91m\$PWD\e[m\n\$ "
else
  PS1="\n{\t} [\u@\h]: \e[36m\w\e[m\n\$ "
fi
PS2="=> "
PS3="==> "
PS4="===> "
export PS1 PS2 PS3 PS4

# Environment
PATH="$HOME/.bin:$PATH"
#PATH="/opt/local/sbin:/opt/local/bin:$PATH"         # MacPorts packages
#PATH="/opt/homebrew/sbin:/opt/homebrew/bin:$PATH"   # Homebrew packages
export PATH
export DISABLE_PROXY=true
#export DOTNET_CLI_TELEMETRY_OPTOUT=true
#export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
#export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
#export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"

# Read additional configs
if [ -d $HOME/.bashrc.d/ ]; then
  for cfile in $HOME/.bashrc.d/*; do
    . $cfile
  done
  unset cfile
fi
